# DO NOT DELETE THIS LINE -- make depend depends on it.
main.o: main.c config.h /usr/lib/avr/include/avr/io.h \
 /usr/lib/avr/include/avr/sfr_defs.h /usr/lib/avr/include/inttypes.h \
 /usr/lib/gcc/avr/4.8.2/include/stdint.h /usr/lib/avr/include/stdint.h \
 /usr/lib/avr/include/avr/iom32m1.h /usr/lib/avr/include/avr/portpins.h \
 /usr/lib/avr/include/avr/common.h /usr/lib/avr/include/avr/version.h \
 /usr/lib/avr/include/avr/fuse.h /usr/lib/avr/include/avr/lock.h \
 /usr/lib/avr/include/avr/interrupt.h can_lib.h can_drv.h
