# DO NOT DELETE THIS LINE -- make depend depends on it.
main.o: main.c ../header_and_config/LUR7.h /usr/lib/avr/include/avr/io.h \
 /usr/lib/avr/include/avr/sfr_defs.h /usr/lib/avr/include/inttypes.h \
 /usr/lib/gcc/avr/4.8.1/include/stdint.h /usr/lib/avr/include/stdint.h \
 /usr/lib/avr/include/avr/iom32m1.h /usr/lib/avr/include/avr/portpins.h \
 /usr/lib/avr/include/avr/common.h /usr/lib/avr/include/avr/version.h \
 /usr/lib/avr/include/avr/fuse.h /usr/lib/avr/include/avr/lock.h \
 /usr/lib/avr/include/avr/interrupt.h /usr/lib/avr/include/util/atomic.h \
 /usr/lib/avr/include/util/delay.h \
 /usr/lib/avr/include/util/delay_basic.h /usr/lib/avr/include/math.h \
 ../header_and_config/LUR7_io.h ../header_and_config/LUR7_adc.h \
 ../header_and_config/LUR7_ancomp.h ../header_and_config/LUR7_can.h \
 ../header_and_config/LUR7_interrupt.h ../header_and_config/LUR7_power.h \
 ../header_and_config/LUR7_timer0.h ../header_and_config/LUR7_timer1.h \
 FAT32.h SD_routines.h SPI_routines.h
LUR7_io.o: ../header_and_config/LUR7_io.c \
 /usr/lib/avr/include/avr/cpufunc.h ../header_and_config/LUR7.h \
 /usr/lib/avr/include/avr/io.h /usr/lib/avr/include/avr/sfr_defs.h \
 /usr/lib/avr/include/inttypes.h /usr/lib/gcc/avr/4.8.1/include/stdint.h \
 /usr/lib/avr/include/stdint.h /usr/lib/avr/include/avr/iom32m1.h \
 /usr/lib/avr/include/avr/portpins.h /usr/lib/avr/include/avr/common.h \
 /usr/lib/avr/include/avr/version.h /usr/lib/avr/include/avr/fuse.h \
 /usr/lib/avr/include/avr/lock.h /usr/lib/avr/include/avr/interrupt.h \
 /usr/lib/avr/include/util/atomic.h /usr/lib/avr/include/util/delay.h \
 /usr/lib/avr/include/util/delay_basic.h /usr/lib/avr/include/math.h \
 ../header_and_config/LUR7_io.h ../header_and_config/LUR7_adc.h \
 ../header_and_config/LUR7_ancomp.h ../header_and_config/LUR7_can.h \
 ../header_and_config/LUR7_interrupt.h ../header_and_config/LUR7_power.h \
 ../header_and_config/LUR7_timer0.h ../header_and_config/LUR7_timer1.h
LUR7_adc.o: ../header_and_config/LUR7_adc.c ../header_and_config/LUR7.h \
 /usr/lib/avr/include/avr/io.h /usr/lib/avr/include/avr/sfr_defs.h \
 /usr/lib/avr/include/inttypes.h /usr/lib/gcc/avr/4.8.1/include/stdint.h \
 /usr/lib/avr/include/stdint.h /usr/lib/avr/include/avr/iom32m1.h \
 /usr/lib/avr/include/avr/portpins.h /usr/lib/avr/include/avr/common.h \
 /usr/lib/avr/include/avr/version.h /usr/lib/avr/include/avr/fuse.h \
 /usr/lib/avr/include/avr/lock.h /usr/lib/avr/include/avr/interrupt.h \
 /usr/lib/avr/include/util/atomic.h /usr/lib/avr/include/util/delay.h \
 /usr/lib/avr/include/util/delay_basic.h /usr/lib/avr/include/math.h \
 ../header_and_config/LUR7_io.h ../header_and_config/LUR7_adc.h \
 ../header_and_config/LUR7_ancomp.h ../header_and_config/LUR7_can.h \
 ../header_and_config/LUR7_interrupt.h ../header_and_config/LUR7_power.h \
 ../header_and_config/LUR7_timer0.h ../header_and_config/LUR7_timer1.h
LUR7_ancomp.o: ../header_and_config/LUR7_ancomp.c \
 ../header_and_config/LUR7.h /usr/lib/avr/include/avr/io.h \
 /usr/lib/avr/include/avr/sfr_defs.h /usr/lib/avr/include/inttypes.h \
 /usr/lib/gcc/avr/4.8.1/include/stdint.h /usr/lib/avr/include/stdint.h \
 /usr/lib/avr/include/avr/iom32m1.h /usr/lib/avr/include/avr/portpins.h \
 /usr/lib/avr/include/avr/common.h /usr/lib/avr/include/avr/version.h \
 /usr/lib/avr/include/avr/fuse.h /usr/lib/avr/include/avr/lock.h \
 /usr/lib/avr/include/avr/interrupt.h /usr/lib/avr/include/util/atomic.h \
 /usr/lib/avr/include/util/delay.h \
 /usr/lib/avr/include/util/delay_basic.h /usr/lib/avr/include/math.h \
 ../header_and_config/LUR7_io.h ../header_and_config/LUR7_adc.h \
 ../header_and_config/LUR7_ancomp.h ../header_and_config/LUR7_can.h \
 ../header_and_config/LUR7_interrupt.h ../header_and_config/LUR7_power.h \
 ../header_and_config/LUR7_timer0.h ../header_and_config/LUR7_timer1.h
LUR7_can.o: ../header_and_config/LUR7_can.c ../header_and_config/LUR7.h \
 /usr/lib/avr/include/avr/io.h /usr/lib/avr/include/avr/sfr_defs.h \
 /usr/lib/avr/include/inttypes.h /usr/lib/gcc/avr/4.8.1/include/stdint.h \
 /usr/lib/avr/include/stdint.h /usr/lib/avr/include/avr/iom32m1.h \
 /usr/lib/avr/include/avr/portpins.h /usr/lib/avr/include/avr/common.h \
 /usr/lib/avr/include/avr/version.h /usr/lib/avr/include/avr/fuse.h \
 /usr/lib/avr/include/avr/lock.h /usr/lib/avr/include/avr/interrupt.h \
 /usr/lib/avr/include/util/atomic.h /usr/lib/avr/include/util/delay.h \
 /usr/lib/avr/include/util/delay_basic.h /usr/lib/avr/include/math.h \
 ../header_and_config/LUR7_io.h ../header_and_config/LUR7_adc.h \
 ../header_and_config/LUR7_ancomp.h ../header_and_config/LUR7_can.h \
 ../header_and_config/LUR7_interrupt.h ../header_and_config/LUR7_power.h \
 ../header_and_config/LUR7_timer0.h ../header_and_config/LUR7_timer1.h
LUR7_interrupt.o: ../header_and_config/LUR7_interrupt.c \
 ../header_and_config/LUR7.h /usr/lib/avr/include/avr/io.h \
 /usr/lib/avr/include/avr/sfr_defs.h /usr/lib/avr/include/inttypes.h \
 /usr/lib/gcc/avr/4.8.1/include/stdint.h /usr/lib/avr/include/stdint.h \
 /usr/lib/avr/include/avr/iom32m1.h /usr/lib/avr/include/avr/portpins.h \
 /usr/lib/avr/include/avr/common.h /usr/lib/avr/include/avr/version.h \
 /usr/lib/avr/include/avr/fuse.h /usr/lib/avr/include/avr/lock.h \
 /usr/lib/avr/include/avr/interrupt.h /usr/lib/avr/include/util/atomic.h \
 /usr/lib/avr/include/util/delay.h \
 /usr/lib/avr/include/util/delay_basic.h /usr/lib/avr/include/math.h \
 ../header_and_config/LUR7_io.h ../header_and_config/LUR7_adc.h \
 ../header_and_config/LUR7_ancomp.h ../header_and_config/LUR7_can.h \
 ../header_and_config/LUR7_interrupt.h ../header_and_config/LUR7_power.h \
 ../header_and_config/LUR7_timer0.h ../header_and_config/LUR7_timer1.h
LUR7_power.o: ../header_and_config/LUR7_power.c \
 ../header_and_config/LUR7.h /usr/lib/avr/include/avr/io.h \
 /usr/lib/avr/include/avr/sfr_defs.h /usr/lib/avr/include/inttypes.h \
 /usr/lib/gcc/avr/4.8.1/include/stdint.h /usr/lib/avr/include/stdint.h \
 /usr/lib/avr/include/avr/iom32m1.h /usr/lib/avr/include/avr/portpins.h \
 /usr/lib/avr/include/avr/common.h /usr/lib/avr/include/avr/version.h \
 /usr/lib/avr/include/avr/fuse.h /usr/lib/avr/include/avr/lock.h \
 /usr/lib/avr/include/avr/interrupt.h /usr/lib/avr/include/util/atomic.h \
 /usr/lib/avr/include/util/delay.h \
 /usr/lib/avr/include/util/delay_basic.h /usr/lib/avr/include/math.h \
 ../header_and_config/LUR7_io.h ../header_and_config/LUR7_adc.h \
 ../header_and_config/LUR7_ancomp.h ../header_and_config/LUR7_can.h \
 ../header_and_config/LUR7_interrupt.h ../header_and_config/LUR7_power.h \
 ../header_and_config/LUR7_timer0.h ../header_and_config/LUR7_timer1.h
LUR7_timer0.o: ../header_and_config/LUR7_timer0.c \
 ../header_and_config/LUR7.h /usr/lib/avr/include/avr/io.h \
 /usr/lib/avr/include/avr/sfr_defs.h /usr/lib/avr/include/inttypes.h \
 /usr/lib/gcc/avr/4.8.1/include/stdint.h /usr/lib/avr/include/stdint.h \
 /usr/lib/avr/include/avr/iom32m1.h /usr/lib/avr/include/avr/portpins.h \
 /usr/lib/avr/include/avr/common.h /usr/lib/avr/include/avr/version.h \
 /usr/lib/avr/include/avr/fuse.h /usr/lib/avr/include/avr/lock.h \
 /usr/lib/avr/include/avr/interrupt.h /usr/lib/avr/include/util/atomic.h \
 /usr/lib/avr/include/util/delay.h \
 /usr/lib/avr/include/util/delay_basic.h /usr/lib/avr/include/math.h \
 ../header_and_config/LUR7_io.h ../header_and_config/LUR7_adc.h \
 ../header_and_config/LUR7_ancomp.h ../header_and_config/LUR7_can.h \
 ../header_and_config/LUR7_interrupt.h ../header_and_config/LUR7_power.h \
 ../header_and_config/LUR7_timer0.h ../header_and_config/LUR7_timer1.h
LUR7_timer1.o: ../header_and_config/LUR7_timer1.c \
 ../header_and_config/LUR7.h /usr/lib/avr/include/avr/io.h \
 /usr/lib/avr/include/avr/sfr_defs.h /usr/lib/avr/include/inttypes.h \
 /usr/lib/gcc/avr/4.8.1/include/stdint.h /usr/lib/avr/include/stdint.h \
 /usr/lib/avr/include/avr/iom32m1.h /usr/lib/avr/include/avr/portpins.h \
 /usr/lib/avr/include/avr/common.h /usr/lib/avr/include/avr/version.h \
 /usr/lib/avr/include/avr/fuse.h /usr/lib/avr/include/avr/lock.h \
 /usr/lib/avr/include/avr/interrupt.h /usr/lib/avr/include/util/atomic.h \
 /usr/lib/avr/include/util/delay.h \
 /usr/lib/avr/include/util/delay_basic.h /usr/lib/avr/include/math.h \
 ../header_and_config/LUR7_io.h ../header_and_config/LUR7_adc.h \
 ../header_and_config/LUR7_ancomp.h ../header_and_config/LUR7_can.h \
 ../header_and_config/LUR7_interrupt.h ../header_and_config/LUR7_power.h \
 ../header_and_config/LUR7_timer0.h ../header_and_config/LUR7_timer1.h
FAT32.o: FAT32.c ../header_and_config/LUR7.h \
 /usr/lib/avr/include/avr/io.h /usr/lib/avr/include/avr/sfr_defs.h \
 /usr/lib/avr/include/inttypes.h /usr/lib/gcc/avr/4.8.1/include/stdint.h \
 /usr/lib/avr/include/stdint.h /usr/lib/avr/include/avr/iom32m1.h \
 /usr/lib/avr/include/avr/portpins.h /usr/lib/avr/include/avr/common.h \
 /usr/lib/avr/include/avr/version.h /usr/lib/avr/include/avr/fuse.h \
 /usr/lib/avr/include/avr/lock.h /usr/lib/avr/include/avr/interrupt.h \
 /usr/lib/avr/include/util/atomic.h /usr/lib/avr/include/util/delay.h \
 /usr/lib/avr/include/util/delay_basic.h /usr/lib/avr/include/math.h \
 ../header_and_config/LUR7_io.h ../header_and_config/LUR7_adc.h \
 ../header_and_config/LUR7_ancomp.h ../header_and_config/LUR7_can.h \
 ../header_and_config/LUR7_interrupt.h ../header_and_config/LUR7_power.h \
 ../header_and_config/LUR7_timer0.h ../header_and_config/LUR7_timer1.h \
 /usr/lib/avr/include/avr/pgmspace.h \
 /usr/lib/gcc/avr/4.8.1/include/stddef.h FAT32.h SD_routines.h
SD_routines.o: SD_routines.c ../header_and_config/LUR7.h \
 /usr/lib/avr/include/avr/io.h /usr/lib/avr/include/avr/sfr_defs.h \
 /usr/lib/avr/include/inttypes.h /usr/lib/gcc/avr/4.8.1/include/stdint.h \
 /usr/lib/avr/include/stdint.h /usr/lib/avr/include/avr/iom32m1.h \
 /usr/lib/avr/include/avr/portpins.h /usr/lib/avr/include/avr/common.h \
 /usr/lib/avr/include/avr/version.h /usr/lib/avr/include/avr/fuse.h \
 /usr/lib/avr/include/avr/lock.h /usr/lib/avr/include/avr/interrupt.h \
 /usr/lib/avr/include/util/atomic.h /usr/lib/avr/include/util/delay.h \
 /usr/lib/avr/include/util/delay_basic.h /usr/lib/avr/include/math.h \
 ../header_and_config/LUR7_io.h ../header_and_config/LUR7_adc.h \
 ../header_and_config/LUR7_ancomp.h ../header_and_config/LUR7_can.h \
 ../header_and_config/LUR7_interrupt.h ../header_and_config/LUR7_power.h \
 ../header_and_config/LUR7_timer0.h ../header_and_config/LUR7_timer1.h \
 SD_routines.h SPI_routines.h
SPI_routines.o: SPI_routines.c ../header_and_config/LUR7.h \
 /usr/lib/avr/include/avr/io.h /usr/lib/avr/include/avr/sfr_defs.h \
 /usr/lib/avr/include/inttypes.h /usr/lib/gcc/avr/4.8.1/include/stdint.h \
 /usr/lib/avr/include/stdint.h /usr/lib/avr/include/avr/iom32m1.h \
 /usr/lib/avr/include/avr/portpins.h /usr/lib/avr/include/avr/common.h \
 /usr/lib/avr/include/avr/version.h /usr/lib/avr/include/avr/fuse.h \
 /usr/lib/avr/include/avr/lock.h /usr/lib/avr/include/avr/interrupt.h \
 /usr/lib/avr/include/util/atomic.h /usr/lib/avr/include/util/delay.h \
 /usr/lib/avr/include/util/delay_basic.h /usr/lib/avr/include/math.h \
 ../header_and_config/LUR7_io.h ../header_and_config/LUR7_adc.h \
 ../header_and_config/LUR7_ancomp.h ../header_and_config/LUR7_can.h \
 ../header_and_config/LUR7_interrupt.h ../header_and_config/LUR7_power.h \
 ../header_and_config/LUR7_timer0.h ../header_and_config/LUR7_timer1.h \
 SPI_routines.h
